<a href="https://colab.research.google.com/github/Ozyura1/Laprak-Semester4/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## GUIDED 1


In [1]:
import numpy as np

x = np.array  ([3,7,2,9])
y = np.array  ([4,7,1,4])

z = x + y

print(z)
print(z.tolist())

[ 7 14  3 13]
[7, 14, 3, 13]


## GUIDED 2

In [4]:
import numpy as np

x = np.array  ([3,7,2,9])
y = np.array  ([4,7,1,4])

z = np.concatenate ((x,y ))

print(z)

[3 7 2 9 4 7 1 4]


## GUIDED 3

In [8]:
x = np.array([[40,29,63],
             [45,70,30],
             [30,70,50]])
print("Dimensi array x:", x.ndim)

Dimensi array x: 2


## GUIDED 4

In [12]:
x = np.array([[40,29,63],
             [45,70,30]])
y = np.array([4.4, 7.2, 9.0])

print("Shape x:", x.shape)
print("Size x:", x.size)
print("Type x:", x.dtype)
print("Type y:", y.dtype)

Shape x: (2, 3)
Size x: 6
Type x: int64
Type y: float64


## GUIDED 5

In [30]:
x = np.zeros((3, 5))
y = np.ones((4, 3))
z = np.empty((2, 2))
k = np.arange(0,10,2)
l = np.linspace(0,10,5)
m = np.full((2,3),9)
n = np.random.random,((2, 3))
o = np.random.randint(0, 50, size = (2, 3))

print(x)
print(y)
print(z)
print(k)
print(l)
print(m)
print(n)
print(o)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[9 9 9]
 [9 9 9]]
(<built-in method random of numpy.random.mtrand.RandomState object at 0x7f7a36d56d40>, (2, 3))
[[28 17 31]
 [ 5 49 21]]


##GUIDED 6

In [34]:
def penjumlahan(bilangan1, bilangan2):
  return bilangan1 + bilangan2
x = np.fromfunction(penjumlahan, (3, 2), dtype=int )

print(x)

[[0 1]
 [1 2]
 [2 3]]


## GUIDED 7

In [40]:
x = np.array([4, 7, 9, 2, 5])

# Menghapus elemen pada indeks 2
x = np.delete(x, 2)
print(x)

y = np.array([4, 7, 9, 2, 5])
# Mengganti elemen yang lebih besar dari 3 dengan NaN
y = np.where(y > 3, np.nan, y)
# Menghapus elemen NaN dari array
y = y[~np.isnan(y)]
print(X)

[4 7 2 5]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## GUIDED 8


In [43]:
import numpy as np
x = np.array([4, 7, 9, 2, 5])
y = np.sort(x)

print(y)

[2 4 5 7 9]


## GUIDED 9

In [48]:
import numpy as np


x = np.array([4, 7, 9, 2, 5])
y = np.sort([x])
print(x[2])

# Slicing
subset = x[1:4]
print(subset)

9
[7 9 2]


## GUIDED 10

In [47]:
# prompt: x = np.array([3, 2 6, 5])

x = np.array([3, 2, 6, 5])

y = x.view()
y[0] = 99

print("Array asli :", x)
print("Shallow copy :", y)


Array asli : [99  2  6  5]
Shallow copy : [99  2  6  5]


## GUIDED 11

In [51]:
import numpy as np

#shallow copy
x = np.array([3, 2, 6, 5])
y = x.copy()
y[0] = 99

print("Array asli:", x)
print("Array copy:", y)

Array asli: [3 2 6 5]
Array copy: [99  2  6  5]


## GUIDED 12

In [52]:
x = np.array ([7, 2, 9, 3])

#Nilai Maksimum
max_value = np.max(x)
print ("Nilai maks : ", max_value)

#Nilai Minimum
min_value = np.min(x)
print ("Nilai min : ", min_value)

#Penjumlahan
sum_value = np.sum(x)
print("Jumlah total: ", sum_value)

#Rata - rata
mean_value = np.mean(x)
print("Rata - rata: ", mean_value)

Nilai maks :  9
Nilai min :  2
Jumlah total:  21
Rata - rata:  5.25


## GUIDED 13

## GUIDED 14

In [ ]:
x = np.array([4, 9, 3, 7, 1, 4])

# Mengubah ne=menjadi array 2D dengan 2 baris dan 3 kolom
y =