<a href="https://colab.research.google.com/github/Ozyura1/Laprak-Semester4/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## GUIDED 1


In [ ]:
import numpy as np

x = np.array  ([3,7,2,9])
y = np.array  ([4,7,1,4])

z = x + y

print(z)
print(z.tolist())

[ 7 14  3 13]
[7, 14, 3, 13]


Program ini menggunakan NumPy untuk menjumlahkan dua array dan mencetak hasilnya baik sebagai array maupun list, menunjukkan kemudahan dalam melakukan operasi matematis pada data numerik

## GUIDED 2

In [ ]:
import numpy as np

x = np.array  ([3,7,2,9])
y = np.array  ([4,7,1,4])

z = np.concatenate ((x,y ))

print(z)

[3 7 2 9 4 7 1 4]


Program ini menggunakan NumPy untuk menggabungkan dua array `x` dan `y` menjadi satu array baru `z` menggunakan fungsi `concatenate`, kemudian mencetak hasilnya, yang menunjukkan kemudahan dalam mengelola dan menggabungkan data numerik.

## GUIDED 3

In [ ]:
x = np.array([[40,29,63],
             [45,70,30],
             [30,70,50]])
print("Dimensi array x:", x.ndim)

Dimensi array x: 2


Program ini menggunakan NumPy untuk membuat array 2D `x` dan mencetak dimensinya menggunakan atribut `ndim`, yang menunjukkan bahwa array tersebut memiliki 2 dimensi, berguna untuk memahami struktur data dalam analisis numerik.

## GUIDED 4

In [ ]:
x = np.array([[40,29,63],
             [45,70,30]])
y = np.array([4.4, 7.2, 9.0])

print("Shape x:", x.shape)
print("Size x:", x.size)
print("Type x:", x.dtype)
print("Type y:", y.dtype)

Shape x: (2, 3)
Size x: 6
Type x: int64
Type y: float64


Program ini menggunakan NumPy untuk membuat array 2D `x` dan array 1D `y`, lalu mencetak informasi seperti bentuk (shape), jumlah elemen (size), dan tipe data (dtype) dari `x`, serta tipe data `y`, membantu memahami struktur dan karakteristik data dalam analisis numerik.

## GUIDED 5

In [ ]:
x = np.zeros((3, 5))
y = np.ones((4, 3))
z = np.empty((2, 2))
k = np.arange(0,10,2)
l = np.linspace(0,10,5)
m = np.full((2,3),9)
n = np.random.random,((2, 3))
o = np.random.randint(0, 50, size = (2, 3))

print(x)
print(y)
print(z)
print(k)
print(l)
print(m)
print(n)
print(o)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[9 9 9]
 [9 9 9]]
(<built-in method random of numpy.random.mtrand.RandomState object at 0x7f7a36d56d40>, (2, 3))
[[28 17 31]
 [ 5 49 21]]


Program ini menggunakan NumPy untuk membuat berbagai jenis array, seperti array nol (`x`), array satu (`y`), array kosong (`z`), array dengan rentang nilai (`k` dan `l`), array berisi nilai konstan (`m`), serta array acak (`n` dan `o`), kemudian mencetak semua array tersebut untuk menunjukkan cara membuat dan memanipulasi data numerik dengan NumPy.

##GUIDED 6

In [ ]:
def penjumlahan(bilangan1, bilangan2):
  return bilangan1 + bilangan2
x = np.fromfunction(penjumlahan, (3, 2), dtype=int )

print(x)

[[0 1]
 [1 2]
 [2 3]]


Program ini menggunakan NumPy untuk membuat array 2D `x` dengan fungsi `fromfunction`, yang menerapkan fungsi `penjumlahan` pada setiap indeks array untuk menghasilkan nilai, sehingga mencetak array yang elemennya merupakan hasil penjumlahan indeks baris dan kolomnya, menunjukkan cara membuat array berbasis fungsi dengan NumPy.

## GUIDED 7

In [ ]:
x = np.array([4, 7, 9, 2, 5])

# Menghapus elemen pada indeks 2
x = np.delete(x, 2)
print(x)

y = np.array([4, 7, 9, 2, 5])
# Mengganti elemen yang lebih besar dari 3 dengan NaN
y = np.where(y > 3, np.nan, y)
# Menghapus elemen NaN dari array
y = y[~np.isnan(y)]
print(X)

[4 7 2 5]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Program ini menggunakan NumPy untuk memanipulasi array: pertama, menghapus elemen pada indeks 2 dari array `x` menggunakan `np.delete`, dan kedua, mengganti elemen yang lebih besar dari 3 dengan `NaN` pada array `y` menggunakan `np.where`, lalu menghapus elemen `NaN` dengan `~np.isnan`, sehingga mencetak array yang telah dimodifikasi, menunjukkan cara menghapus dan mengganti elemen dalam array dengan NumPy.

## GUIDED 8


In [ ]:
import numpy as np
x = np.array([4, 7, 9, 2, 5])
y = np.sort(x)

print(y)

[2 4 5 7 9]


Program ini menggunakan NumPy untuk membuat array `x` dan kemudian mengurutkan elemen-elemen dalam array tersebut menggunakan fungsi `np.sort`, menyimpan hasilnya dalam array baru `y`, dan mencetak array yang telah diurutkan, menunjukkan kemudahan dalam melakukan operasi pengurutan pada data numerik dengan NumPy.

## GUIDED 9

In [ ]:
import numpy as np


x = np.array([4, 7, 9, 2, 5])
y = np.sort([x])
print(x[2])

# Slicing
subset = x[1:4]
print(subset)

9
[7 9 2]


Program ini menggunakan NumPy untuk membuat array `x`, mengurutkan elemennya dengan `np.sort`, mencetak elemen pada indeks 2, dan melakukan slicing untuk mengambil subset elemen dari indeks 1 hingga 3, menunjukkan cara mengakses dan memanipulasi elemen array dengan NumPy.

## GUIDED 10

In [ ]:
# prompt: x = np.array([3, 2 6, 5])

x = np.array([3, 2, 6, 5])

y = x.view()
y[0] = 99

print("Array asli :", x)
print("Shallow copy :", y)


Array asli : [99  2  6  5]
Shallow copy : [99  2  6  5]


Program ini menggunakan NumPy untuk membuat array `x` dan kemudian membuat salinan dangkal (shallow copy) `y` dari array tersebut menggunakan metode `view()`. Ketika elemen pertama dari `y` diubah menjadi 99, perubahan tersebut juga tercermin pada array asli `x`, karena `y` dan `x` berbagi data yang sama. Program ini mencetak kedua array untuk menunjukkan bahwa perubahan pada salinan mempengaruhi array asli, yang menggambarkan perilaku salinan dangkal dalam NumPy.

## GUIDED 11

In [ ]:
import numpy as np

#shallow copy
x = np.array([3, 2, 6, 5])
y = x.copy()
y[0] = 99

print("Array asli:", x)
print("Array copy:", y)

Array asli: [3 2 6 5]
Array copy: [99  2  6  5]


Program ini menggunakan NumPy untuk membuat array `x` dan kemudian membuat salinan dalam (deep copy) `y` dari array tersebut menggunakan metode `copy()`. Ketika elemen pertama dari `y` diubah menjadi 99, perubahan tersebut tidak mempengaruhi array asli `x`, karena `y` adalah salinan yang terpisah. Program ini mencetak kedua array untuk menunjukkan bahwa perubahan pada salinan tidak mempengaruhi array asli, yang menggambarkan perilaku salinan dalam dalam NumPy.

## GUIDED 12

In [ ]:
x = np.array ([7, 2, 9, 3])

#Nilai Maksimum
max_value = np.max(x)
print ("Nilai maks : ", max_value)

#Nilai Minimum
min_value = np.min(x)
print ("Nilai min : ", min_value)

#Penjumlahan
sum_value = np.sum(x)
print("Jumlah total: ", sum_value)

#Rata - rata
mean_value = np.mean(x)
print("Rata - rata: ", mean_value)

Nilai maks :  9
Nilai min :  2
Jumlah total:  21
Rata - rata:  5.25


Program ini menggunakan NumPy untuk melakukan analisis dasar pada array `x`, yang berisi beberapa nilai. Pertama, program menghitung dan mencetak nilai maksimum menggunakan `np.max()`, nilai minimum menggunakan `np.min()`, jumlah total elemen menggunakan `np.sum()`, dan rata-rata menggunakan `np.mean()`. Hasilnya memberikan informasi statistik yang berguna tentang data dalam array, menunjukkan kemudahan dalam melakukan perhitungan statistik dengan NumPy.

## GUIDED 13

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = x.transpose()
print(y)

[[1 4]
 [2 5]
 [3 6]]


Program ini menggunakan NumPy untuk membuat array 2D `x` dan kemudian melakukan operasi transpose menggunakan `x.transpose()`, yang menghasilkan array `y` dengan baris dan kolom yang ditukar. Program ini mencetak array hasil transpose, menunjukkan cara mengubah susunan elemen array dari baris ke kolom atau sebaliknya dengan NumPy.

## GUIDED 14

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
# Mengubah menjadi array 2D dengan 2 baris dan 3 kolom
y = x.reshape((2, 3))
print(y)

[[1 2 3]
 [4 5 6]]


Program ini menggunakan NumPy untuk mengubah array 1D `x` menjadi array 2D `y` dengan 2 baris dan 3 kolom menggunakan metode `reshape()`. Program ini mencetak array hasil reshape, menunjukkan cara mengubah bentuk array tanpa mengubah data aslinya, yang berguna dalam manipulasi dan analisis data dengan NumPy.

## UNGUIDED 1

In [ ]:
import numpy as np

# Fungsi untuk menampilkan menu
def menu():
    print("\nMenu:")
    print("1. Tambah Data Mahasiswa")
    print("2. Tampilkan Semua Data Mahasiswa")
    print("3. Tampilkan Nilai Tertinggi, Terendah, dan Rata-rata")
    print("4. Cari Mahasiswa")
    print("5. Keluar")

# Inisialisasi array kosong untuk menyimpan data mahasiswa
data_mahasiswa = []

while True:
    menu()
    pilihan = input("Pilih menu (1-5): ")

    if pilihan == '1':
        # Input data mahasiswa
        nama = input("Masukkan Nama Mahasiswa: ")
        nim = input("Masukkan NIM Mahasiswa: ")
        nilai = float(input("Masukkan Nilai Mahasiswa: "))
        tahun_masuk = int(input("Masukkan Tahun Masuk Mahasiswa: "))

        # Menyimpan data mahasiswa dalam bentuk tuple
        data_mahasiswa.append((nama, nim, nilai, tahun_masuk))
        print("Data mahasiswa berhasil ditambahkan.")

    elif pilihan == '2':
        # Tampilkan semua data mahasiswa
        if data_mahasiswa:
            print("\nData Mahasiswa:")
            for idx, (nama, nim, nilai, tahun_masuk) in enumerate(data_mahasiswa, start=1):
                print(f"{idx}. Nama: {nama}, NIM: {nim}, Nilai: {nilai}, Tahun Masuk: {tahun_masuk}")
        else:
            print("Belum ada data mahasiswa.")

    elif pilihan == '3':
        # Tampilkan nilai tertinggi, terendah, dan rata-rata
        if data_mahasiswa:
            nilai_array = np.array([nilai for _, _, nilai, _ in data_mahasiswa])
            nilai_tertinggi = np.max(nilai_array)
            nilai_terendah = np.min(nilai_array)
            nilai_rata_rata = np.mean(nilai_array)

            print(f"Nilai Tertinggi: {nilai_tertinggi}")
            print(f"Nilai Terendah: {nilai_terendah}")
            print(f"Nilai Rata-rata: {nilai_rata_rata}")
        else:
            print("Belum ada data mahasiswa.")

    elif pilihan == '4':
        # Cari mahasiswa berdasarkan NIM atau Nama
        cari = input("Masukkan NIM atau Nama yang dicari: ")
        hasil_cari = [data for data in data_mahasiswa if cari in data]

        if hasil_cari:
            print("\nHasil Pencarian:")
            for (nama, nim, nilai, tahun_masuk) in hasil_cari:
                print(f"Nama: {nama}, NIM: {nim}, Nilai: {nilai}, Tahun Masuk: {tahun_masuk}")
        else:
            print("Mahasiswa tidak ditemukan.")

    elif pilihan == '5':
        print("Keluar dari program.")
        break

    else:
        print("Pilihan tidak valid. Silakan pilih menu yang tersedia.")


Menu:
1. Tambah Data Mahasiswa
2. Tampilkan Semua Data Mahasiswa
3. Tampilkan Nilai Tertinggi, Terendah, dan Rata-rata
4. Cari Mahasiswa
5. Keluar
Pilih menu (1-5): 1
Masukkan Nama Mahasiswa: yanto
Masukkan NIM Mahasiswa: 123
Masukkan Nilai Mahasiswa: 90
Masukkan Tahun Masuk Mahasiswa: 2025
Data mahasiswa berhasil ditambahkan.

Menu:
1. Tambah Data Mahasiswa
2. Tampilkan Semua Data Mahasiswa
3. Tampilkan Nilai Tertinggi, Terendah, dan Rata-rata
4. Cari Mahasiswa
5. Keluar
Pilih menu (1-5): 1
Masukkan Nama Mahasiswa: yanti
Masukkan NIM Mahasiswa: 321
Masukkan Nilai Mahasiswa: 80
Masukkan Tahun Masuk Mahasiswa: 2025
Data mahasiswa berhasil ditambahkan.

Menu:
1. Tambah Data Mahasiswa
2. Tampilkan Semua Data Mahasiswa
3. Tampilkan Nilai Tertinggi, Terendah, dan Rata-rata
4. Cari Mahasiswa
5. Keluar
Pilih menu (1-5): 2

Data Mahasiswa:
1. Nama: yanto, NIM: 123, Nilai: 90.0, Tahun Masuk: 2025
2. Nama: yanti, NIM: 321, Nilai: 80.0, Tahun Masuk: 2025

Menu:
1. Tambah Data Mahasiswa
2. Tampil

Program ini adalah aplikasi manajemen data mahasiswa yang menggunakan NumPy untuk menghitung nilai tertinggi, terendah, dan rata-rata. Penjelasan lebih lanjut:

1. **Menu**: Program menampilkan menu dengan pilihan untuk menambah data mahasiswa, menampilkan semua data, menampilkan statistik nilai, mencari mahasiswa, dan keluar dari program.

2. **Input Data Mahasiswa**: Pengguna dapat memasukkan nama, NIM, nilai, dan tahun masuk mahasiswa. Data disimpan dalam bentuk tuple dalam list `data_mahasiswa`.

3. **Tampilkan Semua Data Mahasiswa**: Jika ada data yang dimasukkan, program akan menampilkan semua data mahasiswa yang telah disimpan.

4. **Statistik Nilai**: Program menggunakan NumPy untuk menghitung nilai tertinggi, terendah, dan rata-rata dari nilai mahasiswa yang telah dimasukkan. Ini dilakukan dengan mengonversi nilai mahasiswa ke dalam array NumPy dan menggunakan fungsi `np.max()`, `np.min()`, dan `np.mean()`.

5. **Cari Mahasiswa**: Pengguna dapat mencari mahasiswa berdasarkan NIM atau nama. Program akan menampilkan hasil pencarian jika ditemukan.

6. **Keluar**: Program akan berhenti jika pengguna memilih opsi untuk keluar.

Program ini menunjukkan bagaimana menggunakan struktur data dasar dan NumPy untuk mengelola dan menganalisis data dalam aplikasi berbasis teks.

## UNGUIDED 2

In [ ]:
import numpy as np

# Fungsi untuk menampilkan menu
def menu():
    print("\nMenu:")
    print("1. Tambah Data Barang")
    print("2. Tampilkan Semua Data Barang")
    print("3. Tampilkan Total Nilai Inventaris")
    print("4. Cari Barang")
    print("5. Keluar")

# Inisialisasi array kosong untuk menyimpan data barang
data_barang = []

while True:
    menu()
    pilihan = input("Pilih menu (1-5): ")

    if pilihan == '1':
        # Input data barang
        nama_barang = input("Masukkan Nama Barang: ")
        kode_barang = input("Masukkan Kode Barang: ")
        jumlah = int(input("Masukkan Jumlah Barang: "))
        harga_per_unit = float(input("Masukkan Harga Per Unit: "))

        # Menyimpan data barang dalam bentuk tuple
        data_barang.append((nama_barang, kode_barang, jumlah, harga_per_unit))
        print("Data barang berhasil ditambahkan.")

    elif pilihan == '2':
        # Tampilkan semua data barang
        if data_barang:
            print("\nData Barang:")
            for idx, (nama_barang, kode_barang, jumlah, harga_per_unit) in enumerate(data_barang, start=1):
                print(f"{idx}. Nama Barang: {nama_barang}, Kode Barang: {kode_barang}, Jumlah: {jumlah}, Harga Per Unit: {harga_per_unit}")
        else:
            print("Belum ada data barang.")

    elif pilihan == '3':
        # Tampilkan total nilai inventaris
        if data_barang:
            total_nilai = np.sum([jumlah * harga_per_unit for _, _, jumlah, harga_per_unit in data_barang])
            print(f"Total Nilai Inventaris: {total_nilai}")
        else:
            print("Belum ada data barang.")

    elif pilihan == '4':
        # Cari barang berdasarkan KodeBarang atau NamaBarang
        cari = input("Masukkan Kode Barang atau Nama Barang yang dicari: ")
        hasil_cari = [data for data in data_barang if cari in data]

        if hasil_cari:
            print("\nHasil Pencarian:")
            for (nama_barang, kode_barang, jumlah, harga_per_unit) in hasil_cari:
                print(f"Nama Barang: {nama_barang}, Kode Barang: {kode_barang}, Jumlah: {jumlah}, Harga Per Unit: {harga_per_unit}")
        else:
            print("Barang tidak ditemukan.")

    elif pilihan == '5':
        print("Keluar dari program.")
        break

    else:
        print("Pilihan tidak valid. Silakan pilih menu yang tersedia.")


Menu:
1. Tambah Data Barang
2. Tampilkan Semua Data Barang
3. Tampilkan Total Nilai Inventaris
4. Cari Barang
5. Keluar
Pilih menu (1-5): 1
Masukkan Nama Barang: Batu
Masukkan Kode Barang: 1
Masukkan Jumlah Barang: 10
Masukkan Harga Per Unit: 1000
Data barang berhasil ditambahkan.

Menu:
1. Tambah Data Barang
2. Tampilkan Semua Data Barang
3. Tampilkan Total Nilai Inventaris
4. Cari Barang
5. Keluar
Pilih menu (1-5): 1
Masukkan Nama Barang: Air
Masukkan Kode Barang: 2
Masukkan Jumlah Barang: 15
Masukkan Harga Per Unit: 500
Data barang berhasil ditambahkan.

Menu:
1. Tambah Data Barang
2. Tampilkan Semua Data Barang
3. Tampilkan Total Nilai Inventaris
4. Cari Barang
5. Keluar
Pilih menu (1-5): 2

Data Barang:
1. Nama Barang: Batu, Kode Barang: 1, Jumlah: 10, Harga Per Unit: 1000.0
2. Nama Barang: Air, Kode Barang: 2, Jumlah: 15, Harga Per Unit: 500.0

Menu:
1. Tambah Data Barang
2. Tampilkan Semua Data Barang
3. Tampilkan Total Nilai Inventaris
4. Cari Barang
5. Keluar
Pilih menu (1-5)

Program ini adalah aplikasi manajemen inventaris barang yang menggunakan NumPy untuk menghitung total nilai inventaris. Penjelasan lebih lanjutnya:

1. **Menu**: Program menampilkan menu dengan pilihan untuk menambah data barang, menampilkan semua data, menghitung total nilai inventaris, mencari barang, dan keluar dari program.

2. **Input Data Barang**: Pengguna dapat memasukkan nama barang, kode barang, jumlah, dan harga per unit. Data disimpan dalam bentuk tuple dalam list `data_barang`.

3. **Tampilkan Semua Data Barang**: Jika ada data yang dimasukkan, program akan menampilkan semua data barang yang telah disimpan.

4. **Total Nilai Inventaris**: Program menggunakan NumPy untuk menghitung total nilai inventaris dengan mengalikan jumlah barang dengan harga per unit untuk setiap barang, kemudian menjumlahkannya menggunakan `np.sum()`.

5. **Cari Barang**: Pengguna dapat mencari barang berdasarkan kode barang atau nama barang. Program akan menampilkan hasil pencarian jika ditemukan.

6. **Keluar**: Program akan berhenti jika pengguna memilih opsi untuk keluar.

Program ini menunjukkan bagaimana menggunakan struktur data dasar dan NumPy untuk mengelola dan menganalisis data inventaris dalam aplikasi berbasis teks.